apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: filterpolicies.getambassador.io
  labels:
    product: aes
    app.kubernetes.io/name: ambassador
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: getambassador.io
  names:
    categories:
    - ambassador-crds
    kind: FilterPolicy
    plural: filterpolicies
    shortNames:
    - fp
    singular: filterpolicy
  scope: Namespaced
  version: v1beta2
  versions:
  - name: v1beta2
    served: true
    storage: false
  - name: v2
    served: true
    storage: true
