---
# app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-app
  namespace: vault
  labels:
    app: vault-agent-demo
spec:
  selector:
    matchLabels:
      app: vault-agent-demo
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-helloworld: "secret/helloworld"
        vault.hashicorp.com/role: "myapp"
      labels:
        app: vault-agent-demo
    spec:
      serviceAccountName: app
      containers:
      - name: vault-app
        image: jweissig/app:0.0.1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  namespace: vault
  labels:
    app: vault-agent-demo
