---
apiVersion: v1
# TODO: make it a deployment
kind: Pod
metadata:
  name: counting
  namesapce: consul
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
spec:
  containers:
  - name: counting
    image: hashicorp/counting-service:0.0.2
    ports:
    - containerPort: 9001
      name: http
    env:
    - name: PORT
      value: 9001
