{{ if contains "datawire/aes" .Values.image.repository }}
---
# Configure DevPortal
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  # This Mapping name is referenced by convention, it's important to leave as-is.
  name: {{ include "ambassador.fullname" . }}-devportal
  labels:
    product: aes
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ include "ambassador.name" . }}-devportal
spec:
  prefix: /documentation/
  rewrite: "/docs/"
  service: "127.0.0.1:8500"
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  # This Mapping name is what the demo uses. Sigh.
  name: {{ include "ambassador.fullname" . }}-devportal-demo
  labels:
    product: aes
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ include "ambassador.name" . }}-devportal-demo
spec:
  prefix: /docs/
  rewrite: "/docs/"
  service: "127.0.0.1:8500"
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  # This Mapping name is referenced by convention, it's important to leave as-is.
  name: {{ include "ambassador.fullname" . }}-devportal-api
  labels:
    product: aes
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ include "ambassador.name" . }}-devportal-api
spec:
  prefix: /openapi/
  rewrite: ""
  service: "127.0.0.1:8500"
---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: {{ include "ambassador.fullname" . }}-internal-access-control
  labels:
    product: aes
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ include "ambassador.name" . }}-internal-access-control
spec:
  rules:
    - host: "*"
      path: "*/.ambassador-internal/*"
      filters:
        - name: {{ include "ambassador.fullname" . }}-internal-access-control
---
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: {{ include "ambassador.fullname" . }}-internal-access-control
  labels:
    product: aes
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ include "ambassador.name" . }}-internal-access-control
spec:
  Internal: {}
{{ end }}