# this is using the ambassador crd, you can also use annotations if you like ... but this is cleaner
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: basicingress
  namespace: default
spec:
  prefix: /basicingress/
  service: basicingress:5000