# Choose an optional name for the datacenter
global:
  datacenter: tiltdc
# Enable the Consul Web UI via a NodePort
ui:
  service:
    enabled: true
    type: 'LoadBalancer'
# Enable Connect for secure communication between nodes
connectInject:
  enabled: true

client:
  enabled: true  
# Use only one Consul server for local development
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
