# oneup app with no ingress, just port mapping
print('Deplying the oneup app')
# HACK: load namespaces on `tilt up` but not on `tilt down`
# this is taken from: https://github.com/windmilleng/tilt/blob/master/integration/Tiltfile
load_namespace = not os.environ.get('SKIP_NAMESPACE', '')
if load_namespace:
  k8s_yaml('k8s/namespace.yaml')

docker_build('oneup', '.')
k8s_yaml('k8s/oneup.yaml')
k8s_resource('oneup', port_forwards=8100)
